create table employees (
id serial primary key,
employee_name varchar(50) not null);

select * from employees;

insert into employees(employee_name)
values ('Maria Oreira'),
       ('Claudia Shiffer'),
       ('Juan Gonzales'),
       ('Jamie Rodrigez'),
       ('Anna Kalshnikova'),
       ('Maria Petersons'),
       ('Grigor Axakhanyan'),
       ('Felix Lewis'),
       ('Tori Garcia'),
       ('Trey Price'),
       ('Francesca Lewis'),
       ('Watson Hayes'),
       ('Natalya Perez'),
       ('Price Carter'),
       ('Kiara Lopez'),
       ('Darren Brooks'),
       ('Brooklin New'),
       ('David Coperfild'),
       ('Fernando Garcia'),
       ('Alfredo Duda'),
       ('Mireia Pablo'),
       ('Gustav Klimt'),
       ('Pablo Picasso'),
       ('Henry Ford'),
       ('Lola Mateo'),
       ('Alejandro Sanz'),
       ('Igor Krutoy'),
       ('Vasyachkin Petrov'),
       ('Goga Alfonso'),
       ('Tata Morta'),
       ('Samuel Perez'),
       ('Alisia Mendez'),
       ('Kati Petersons'),
       ('Georgina Hinze'),
       ('Joseph Hoffman'),
       ('Lola Mateo'),
       ('Gregory Peters'),
       ('Jimmy Griffin'),
       ('Daniel Moore'),
       ('Jason Payne'),
       ('Ernest Glover'),
       ('Robert Stephens'),
       ('Paul Stewart'),
       ('Gary Cook'),
       ('Clyde White'),
       ('Joseph Cole'),
       ('Gary Day'),
       ('Michael Abbott'),
       ('Dale Wade'),
       ('William Reynolds'),
       ('Juan Smith'),
       ('James Sullivan'),
       ('Nathan White'),
       ('Todd Bryant'),
       ('Dennis Walker'),
       ('Michael Reeves'),
       ('Gregory Mills'),
       ('Mike Daniels'),
       ('John Williams'),
       ('John Anderson'),
       ('James Johnson'),
       ('Timothy Dunn'),
       ('Edwin Alexander'),
       ('Paul Spencer'),
       ('Terry Diaz'),
       ('Raymond Jones'),
       ('Edgar Hill'),
       ('Tony Wilson'),
       ('Joseph Armstrong'),
       ('Richard Briggs'),
       ('Mariam Minasyan');
      

create table salary (
id serial primary key,
monthly_salary int not null);

select * from salary;

insert into salary(monthly_salary)
values (1000),
       (1100),
       (1200),
       (1300),
       (1400),
       (1500),
       (1600),
       (1700),
       (1800),
       (1900),
       (2000),
       (2100),
       (2200),
       (2300),
       (2400),
       (2500);


create table employee_salary(
id serial primary key,
employee_id int not null unique,
salary_id int not null
);
insert into employee_salary(employee_id, salary_id)
values (3, 7),
	   (1, 4),
	   (5, 9),
	   (40, 13),
	   (23, 4),
	   (11, 2),
	   (52, 10),
	   (15, 13),
	   (26, 4),
	   (16, 1),
	   (33, 7),
	   (37, 4),
	   (12, 2),
	   (19, 10),
	   (43, 13),
	   (70, 15),
	   (6, 16),
	   (17, 2),
	   (2, 5),
	   (64, 8),
	   (67, 3),
	   (54, 6),
	   (8, 11),
	   (30, 12),
	   (13, 14),
	   (7, 16),
	   (31, 8),
	   (42, 13),
	   (25, 2),
	   (9, 5),
	   (71, 10),
	   (72, 1),
	   (73, 7),
	   (74, 16),
	   (75, 3),
	   (76, 12),
	   (77, 11),
	   (78, 14),
	   (79, 6),
	   (80, 15);

select * from employee_salary;

create table roles(
id serial primary key,
role_name int not null unique
);

alter table roles alter column role_name type varchar(30);

insert into roles(role_name)
values ('Junior Python developer'),
	   ('Middle Python developer'),
	   ('Senior Python developer'),
	   ('Junior Java developer'),
	   ('Middle Java developer'),
	   ('Senior Java developer'),
	   ('Junior JavaScript developer'),
	   ('Middle JavaScript developer'),
	   ('Senior JavaScript developer'),
	   ('Junior Manual QA engineer'),
	   ('Middle Manual QA engineer'),
	   ('Senior Manual QA engineer'),
	   ('Project Manager'),
	   ('Designer'),
	   ('HR'),
	   ('CEO'),
	   ('Sales manager'),
	   ('Junior Automation QA engineer'),
	   ('Middle Automation QA engineer'),
	   ('Senior Automation QA engineer');
	select * from roles;

create table roles_employee(
id serial primary key,
employee_id Int not null unique,
role_id Int not null,
foreign key (employee_id) references employees (id),
foreign key (role_id) references roles (id)
);

insert into roles_employee(employee_id,role_id)
values (7, 2),
       (20, 4),
       (3, 9),
       (5, 13),
       (23, 4),
       (11, 2),
       (10, 9),
       (22, 13),
       (21, 3),
       (34, 4),
       (6, 7),
       (70, 19),
       (30, 10),
       (44, 20),
       (18, 14),
       (60, 1),
       (53, 16),
       (66, 8),
       (51, 17),
       (49, 11),
       (37, 15),
       (13, 6),
       (56, 5),
       (40, 12),
       (25, 18),
       (8, 17),
       (33, 8),
       (47, 11),
       (62, 16),
       (15, 15),
       (1, 1),
       (28, 6),
       (41, 14),
       (59, 5),
       (69, 20),
       (64, 12),
       (16, 10),
       (19, 18),
       (50, 7),
       (45, 19);
      
      select * from roles_employee;
